import uniq from "lodash.uniq"

export const longBookNames = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Solomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation",
  "1 Nephi",
  "2 Nephi",
  "Jacob",
  "Enos",
  "Jarom",
  "Omni",
  "Words of Mormon",
  "Mosiah",
  "Alma",
  "Helaman",
  "3 Nephi",
  "4 Nephi",
  "Mormon",
  "Ether",
  "Moroni",
  "Doctrine and Covenants",
  "Moses",
  "Abraham",
  "Joseph Smith--Matthew",
  "Joseph Smith--History",
  "Articles of Faith",
]

export const shortBookNames = [
  "Gen",
  "Ex",
  "Lev",
  "Num",
  "Deut",
  "Josh",
  "Judg",
  "Ruth",
  "1 Sam",
  "2 Sam",
  "1 Kgs",
  "2 Kgs",
  "1 Chr",
  "2 Chr",
  "Ezra",
  "Neh",
  "Esth",
  "Job",
  "Ps",
  "Prov",
  "Eccl",
  "Song",
  "Isa",
  "Jer",
  "Lam",
  "Ezek",
  "Dan",
  "Hosea",
  "Joel",
  "Amos",
  "Obad",
  "Jonah",
  "Micah",
  "Nahum",
  "Hab",
  "Zeph",
  "Hag",
  "Zech",
  "Mal",
  "Matt",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Rom",
  "1 Cor",
  "2 Cor",
  "Gal",
  "Eph",
  "Philip",
  "Col",
  "1 Thes",
  "2 Thes",
  "1 Tim",
  "2 Tim",
  "Titus",
  "Philem",
  "Heb",
  "James",
  "1 Pet",
  "2 Pet",
  "1 Jn",
  "2 Jn",
  "3 Jn",
  "Jude",
  "Rev",
  "1 Ne",
  "2 Ne",
  "Jacob",
  "Enos",
  "Jarom",
  "Omni",
  "W of M",
  "WofM",
  "Mosiah",
  "Msh",
  "Alma",
  "Hel",
  "3 Ne",
  "4 Ne",
  "Morm",
  "Ether",
  "Moro",
  "D&C",
  "Moses",
  "Abr",
  "JS-M",
  "JS-H",
  "A of F",
  "AofF",
]

export const shortToLongNameMap: { [key: string]: string } = {
  "Gen": "Genesis",
  "Ex": "Exodus",
  "Lev": "Leviticus",
  "Num": "Numbers",
  "Deut": "Deuteronomy",
  "Josh": "Joshua",
  "Judg": "Judges",
  "Ruth": "Ruth",
  "1 Sam": "1 Samuel",
  "2 Sam": "2 Samuel",
  "1 Kgs": "1 Kings",
  "2 Kgs": "2 Kings",
  "1 Chr": "1 Chronicles",
  "2 Chr": "2 Chronicles",
  "Ezra": "Ezra",
  "Neh": "Nehemiah",
  "Esth": "Esther",
  "Job": "Job",
  "Ps": "Psalms",
  "Prov": "Proverbs",
  "Eccl": "Ecclesiastes",
  "Song": "Song of Solomon",
  "Isa": "Isaiah",
  "Jer": "Jeremiah",
  "Lam": "Lamentations",
  "Ezek": "Ezekiel",
  "Dan": "Daniel",
  "Hosea": "Hosea",
  "Joel": "Joel",
  "Amos": "Amos",
  "Obad": "Obadiah",
  "Jonah": "Jonah",
  "Micah": "Micah",
  "Nahum": "Nahum",
  "Hab": "Habakkuk",
  "Zeph": "Zephaniah",
  "Hag": "Haggai",
  "Zech": "Zechariah",
  "Mal": "Malachi",
  "Matt": "Matthew",
  "Mark": "Mark",
  "Luke": "Luke",
  "John": "John",
  "Acts": "Acts",
  "Rom": "Romans",
  "1 Cor": "1 Corinthians",
  "2 Cor": "2 Corinthians",
  "Gal": "Galatians",
  "Eph": "Ephesians",
  "Philip": "Philippians",
  "Col": "Colossians",
  "1 Thes": "1 Thessalonians",
  "2 Thes": "2 Thessalonians",
  "1 Tim": "1 Timothy",
  "2 Tim": "2 Timothy",
  "Titus": "Titus",
  "Philem": "Philemon",
  "Heb": "Hebrews",
  "James": "James",
  "1 Pet": "1 Peter",
  "2 Pet": "2 Peter",
  "1 Jn": "1 John",
  "2 Jn": "2 John",
  "3 Jn": "3 John",
  "Jude": "Jude",
  "Rev": "Revelation",
  "1 Ne": "1 Nephi",
  "2 Ne": "2 Nephi",
  "Jacob": "Jacob",
  "Enos": "Enos",
  "Jarom": "Jarom",
  "Omni": "Omni",
  "W of M": "Words of Mormon",
  "WofM": "Words of Mormon",
  "Mosiah": "Mosiah",
  "Msh": "Mosiah",
  "Alma": "Alma",
  "Hel": "Helaman",
  "3 Ne": "3 Nephi",
  "4 Ne": "4 Nephi",
  "Morm": "Mormon",
  "Ether": "Ether",
  "Moro": "Moroni",
  "D&C": "Doctrine and Covenants",
  "Moses": "Moses",
  "Abr": "Abraham",
  "JS-M": "Joseph Smith--Matthew",
  "JS-H": "Joseph Smith--History",
  "A of F": "Articles of Faith",
  "AofF": "Articles of Faith",
}
// https://en.wikipedia.org/wiki/List_of_Book_of_Mormon_people
export const characterNames = [
  "Aaron",
  "Abinadi",
  "Abinadom",
  "Abish",
  "Aha",
  "Ahah",
  "Akish",
  "Alma",
  "Amaleki",
  "Amalickiah",
  "Amaron",
  "Aminadab",
  "Amgid",
  "Aminadi",
  "Amlici",
  "Ammah",
  "Ammaron",
  "Ammon",
  "Ammoron",
  "Amnigaddah",
  "Amnor",
  "Amoron",
  "Amos",
  "Amulek",
  "Amulon",
  "Antiomno",
  "Antionah",
  "Antionum",
  "Antipus",
  "Archeantus",
  "Benjamin",
  "Brother",
  "Captain",
  "Cezoram",
  "Chemish",
  "Christ",
  "Cohor",
  "Com",
  "Corianton",
  "Coriantor",
  "Coriantum",
  "Coriantumr",
  "Corihor",
  "Corom",
  "Cumenihah",
  "Emer",
  "Emron",
  "Enos",
  "Esrom",
  "Ethem",
  "Ether",
  "Ezias",
  "Gadianton",
  "Gid",
  "Giddianhi",
  "Giddonah",
  "Gideon",
  "Gidgiddonah",
  "Gidgiddoni",
  "Gilead",
  "Gilgah",
  "Gilgal",
  "Hagoth",
  "Hearthom",
  "Helam",
  "Helaman",
  "Helem",
  "Helorum",
  "Hem",
  "Heth",
  "Himni",
  "Isabel",
  "Isaiah",
  "Ishmael",
  "Jacob",
  "Jacom",
  "Jared",
  "Jarom",
  "Jeneum",
  "Jeremiah",
  "Jesus",
  "Jonas",
  "Joseph",
  "Josh",
  "Kib",
  "Kim",
  "Kimnor",
  "King",
  "Kish",
  "Kishkumen",
  "Korihor",
  "Kumen",
  "Kumenonhi",
  "Laban",
  "Lachoneus",
  "Lamah",
  "Laman",
  "Lamoni",
  "Lehi",
  "Lehonti",
  "Lemuel",
  "Levi",
  "Lib",
  "Limhah",
  "Limher",
  "Limhi",
  "Luram",
  "Mahah",
  "Manti",
  "Mathoni",
  "Mathonihah",
  "Morianton",
  "Mormon",
  "Moron",
  "Moroni",
  "Moronihah",
  "Mosiah",
  "Mulek",
  "Muloki",
  "Nehor",
  "Nephi",
  "Nephihah",
  "Neum",
  "Nimrah",
  "Noah",
  "Omer",
  "Omner",
  "Omni",
  "Orihah",
  "Paanchi",
  "Pachus",
  "Pacumeni",
  "Pagag",
  "Pahoran",
  "Riplakish",
  "Sam",
  "Samuel",
  "Sariah",
  "Seantum",
  "Seezoram",
  "Seth",
  "Shared",
  "Shem",
  "Shemnon",
  "Sherem",
  "Shez",
  "Shiblom",
  "Shiblon",
  "Shiz",
  "Shule",
  "Teancum",
  "Teomner",
  "Timothy",
  "Tubaloth",
  "Zarahemla",
  "Zedekiah",
  "Zeezrom",
  "Zemnarihah",
  "Zenephi",
  "Zeniff",
  "Zenock",
  "Zenos",
  "Zerahemnah",
  "Zeram",
  "Zoram",
  "Moses",
  "Three Witnesses",
  "Adam",
  "Enoch",
]

export const namesForChrist = [
  "lord",
  "son",
  "lamb",
  "holy one",
  "god",
  "Well Beloved",
  "Savior",
  "Father",
]

export const nouns = [
  "holy ghost",
  "nephites",
  "lamanites",
  "spirit",
  "liahona",
  "apostles",
  "holy spirit",
  "law of Moses",
  "Saints",
  "Presidency",
  "church",
]

const matchDigitAndSpace = /\d /

export const allNouns = [...characterNames, ...namesForChrist, ...nouns]
export const allBookNames = [...longBookNames, ...shortBookNames]
export const allBookNamesWithoutNumbers: string[] = [...longBookNames, ...shortBookNames].map(
  (name) => name.replace(matchDigitAndSpace, "")
)
export const longBookNamesWithoutNumbers: string[] = uniq(
  longBookNames.map((name) => name.replace(matchDigitAndSpace, ""))
)
